version: '3.2'
services:
  
  lb-haproxy:
    container_name: lb-haproxy-lf720
    build:
      context: haproxy/.
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '8181:8181'
    hostname: lb-haproxy.local
    depends_on:
      - liferay-720-node-1
      - liferay-720-node-2  

  liferay-720-node-1:
    container_name: liferay-720-node-1
    image: borxa/liferay-cluster-node:7.2.0
    environment:
      - ES_OPERATIONMODE=REMOTE
      - ES_CLUSTERNAME=elasticsearch
      - ES_TRANSPORTADDRESSES=es-node-1-lfr720:9300
    ports:
      - '6080:8080'
      - '21311:11311'
      - '8001:8000'
    hostname: liferay-720-node-1.local
    volumes:
      - lfr-720-dl-volume:/data/liferay/document_library
    depends_on:
      - postgres-lfr720
      - redis-lfr720
      - es-node-1-lfr720
      - es-node-2-lfr720
    command: ["/entrypoint.sh", "run"]

  liferay-720-node-2:
    container_name: liferay-720-node-2
    image: borxa/liferay-cluster-node:7.2.0
    ports:
      - '7080:8080'
      - '31311:11311'
      - '8002:8000'
    hostname: liferay-720-node-2.local
    volumes:
      - lfr-720-dl-volume:/data/liferay/document_library
    depends_on:
      - postgres-lfr720
      - redis-lfr720
      - es-node-1-lfr720
      - es-node-2-lfr720
    command: ["/wait-for-node.sh", "liferay-720-node-1:8080", "--", "/entrypoint.sh", "run"]

  postgres-lfr720:
    container_name: postgres-lfr720
    image: postgres:10.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=liferay
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
  
  es-node-1-lfr720:
    container_name: elastic-search-1-lfr720
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - node.name=es-node-1-lfr720
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data1-lfr720:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es-node-2-lfr720:
    container_name: elastic-search-2-lfr720
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - node.name=es-node-2-lfr720
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data2-lfr720:/usr/share/elasticsearch/data

  redis-lfr720:
    container_name: redis-lfr720
    image: redis:alpine

volumes:
  lfr-720-dl-volume:
  es-data1-lfr720:
  es-data2-lfr720:
